# This script reads the bootstrapped mean of:
# 1. Ex post additionality (boot_additionality_[proj].csv)
# 2. Historical project carbon loss rate (boot_project_closs_rate_[proj].csv)
# 3. Historical regional carbon loss rates (boot_regional_closs_rate_[proj].csv)
# generates simple project-based and region-based forecasts as well as mixed forecasts using different historical periods,
# and compares and visualises their performance over different target periods

# It requires the following input variables:
#1. out_path: absolute path (plus prefix) of files generated by this repo, including in forecast_1_setup.r
#2. fig_path: absolute path (plus prefix) of the output figures

rm(list = ls())

#Load packages
library(tidyverse) #ggplot2, dplyr, and stringr used in plotPlacebo/plotBaseline.r: tibble to store labels with bquote()
library(magrittr) #pipe operators
library(corrplot) #corrplot::corrplot
library(MASS) #MASS::stepAIC
library(patchwork)
library(gridExtra)
library(grid) #grid::textGrob, grid::gpar
library(httpgd)

source("PlotModel.r")
hgd()

#Set parallelise plan
plan(multisession, workers = 20)

#Set up wrapper functions for performance metrics
GOF = function(forecast, observed) {
  return(1 - sum((observed - forecast) ^ 2, na.rm = T) / sum((observed - mean(observed, na.rm = T)) ^ 2, na.rm = T))
}
MAPE = function(forecast, observed) {
  return(mean(abs(forecast - observed) / abs(observed), na.rm = T) * 100)
}
MPB = function(forecast, observed) {
  return(mean((forecast - observed) / observed, na.rm = T) * 100)
}

#Define input variables
out_path = "/maps/epr26/ex_ante_forecast_out/out_ongoing" #path of files generated by this repo
fig_path = "/maps/epr26/ex_ante_forecast_out/out_" #path of output figures

project_var = read.csv(paste0(out_path, "_project_var.csv"), header = T)
projects = project_var$ID
t0_vec = project_var$t0
area_ha_vec = project_var$area_ha
cdens_list = project_var %>%
  dplyr::select(ID, cdens_1:cdens_6) %>%
  pivot_longer(cdens_1:cdens_6, names_to = "land.use.class", names_prefix = "cdens_", values_to = "carbon.density") %>%
  split(f = .$ID)


#Load data and express them as relative to project start
boot_add = read.csv(paste0(out_path, "_boot_additionality_arith.csv"), header = T)
boot_closs_obs_cf = read.csv(paste0(out_path, "_boot_closs_obs_cf.csv"), header = T)
boot_closs_obs_p = read.csv(paste0(out_path, "_boot_closs_obs_p.csv"), header = T)
boot_closs_project = read.csv(paste0(out_path, "_boot_closs_project.csv"), header = T)
boot_closs_region = read.csv(paste0(out_path, "_boot_closs_regional.csv"), header = T)

boot_add_list = vector("list", length(projects))
boot_closs_obs_cf_list = vector("list", length(projects))
boot_closs_obs_p_list = vector("list", length(projects))
boot_closs_project_list = vector("list", length(projects))
boot_closs_region_list = vector("list", length(projects))

for(i in seq_along(projects)) {
  t0 = t0_vec[i]
  project_i = projects[i]
  boot_add_list[[i]] = boot_add %>%
      filter(project == project_i) %>%
      mutate(year = year - t0)
  boot_closs_obs_cf_list[[i]] = boot_closs_obs_cf %>%
      filter(project == project_i) %>%
      mutate(year = year - t0)
  boot_closs_obs_p_list[[i]] = boot_closs_obs_p %>%
      filter(project == project_i) %>%
      mutate(year = year - t0)
  boot_closs_project_list[[i]] = boot_closs_project %>%
      filter(project == project_i) %>%
      mutate(year = year - t0)
  boot_closs_region_list[[i]] = boot_closs_region %>%
      filter(project == project_i) %>%
      mutate(year = year - t0)
}

boot_add_rel = list_rbind(boot_add_list)
boot_closs_obs_cf_rel = list_rbind(boot_closs_obs_cf_list)
boot_closs_obs_p_rel = list_rbind(boot_closs_obs_p_list)
boot_closs_project_rel = list_rbind(boot_closs_project_list)
boot_closs_region_rel = list_rbind(boot_closs_region_list)

#Reformat data of observed counterfactual carbon loss rates and make sure every project has 10 years of data
closs_obs_cf = boot_closs_obs_cf_rel %>%
  filter(year <= 10) %>%
  rename(period_target = year, rate_obs = mean) %>%
  complete(project, period_target = 1:10, fill = list(rate_obs = NA_real_))

closs_obs_p = boot_closs_obs_p_rel %>%
  filter(year <= 10) %>%
  rename(period_target = year, rate_obs = mean) %>%
  complete(project, period_target = 1:10, fill = list(rate_obs = NA_real_))

observed_add = boot_add_rel %>%
  filter(year <= 10) %>%
  rename(period_target = year, additionality = mean) %>%
  complete(project, period_target = 1:10, fill = list(additionality = NA_real_))


#Generate simple forecasts from project or regional rates using different historical periods
forecast_prj_list = vector("list", 10 * length(projects))
forecast_reg_list = vector("list", 10 * length(projects))
for(i in 1:10) {
  yr_i = i - 11
  for(k in seq_along(projects)) {
    project_k = projects[k]
    ind = (i - 1) * length(projects) + k

    #project-based forecasts
    rate_project = boot_closs_project_rel %>%
      filter(year == yr_i & project == project_k) %>%
      pull(mean)
    forecast_prj_list[[ind]] = data.frame(period_hist_prj = yr_i, period_hist_reg = NA, period_target = 1:10,
                                          forecast = rate_project, project = project_k)

    #region-based forecasts
    rate_region = boot_closs_region_rel %>%
      filter(year == yr_i & project == project_k) %>%
      pull(mean)
    forecast_reg_list[[ind]] = data.frame(period_hist_prj = NA, period_hist_reg = yr_i, period_target = 1:10,
                                          forecast = rate_region, project = project_k)
  }
}
forecast_prj = list_rbind(forecast_prj_list) %>%
  mutate(type = "Project")
forecast_reg = list_rbind(forecast_reg_list) %>%
  mutate(type = "Region")


#Generate mixed forecasts from project and regional rates using different historical periods
forecast_mix_list = vector("list", 10 * 10 * length(projects))
for(i in 1:10) {
  yr_i = i - 11
  for(j in 1:10) {
    yr_j = j - 11
    for(k in seq_along(projects)) {
      project_k = projects[k]
      ind = (i - 1) * 10 * length(projects) + (j - 1) * length(projects) + k

      #mixed forecasts using project and regional rates
      rate_project = boot_closs_project_rel %>%
        filter(year == yr_i & project == project_k) %>%
        pull(mean)
      rate_region = boot_closs_region_rel %>%
        filter(year == yr_j & project == project_k) %>%
        pull(mean)

      rate_mixed = ((rate_project ^ (9:0)) * (rate_region ^ (0:9))) ^ (1 / 10) #weighted geometric mean

      forecast_mix_list[[ind]] = data.frame(period_hist_prj = yr_i, period_hist_reg = yr_j, period_target = 1:10,
                                            forecast = rate_mixed, project = project_k)
    }
  }
}
forecast_mix = list_rbind(forecast_mix_list) %>%
  mutate(type = "Mixed")

# Merge with observed values
forecast_all = bind_rows(forecast_prj, forecast_reg, forecast_mix) %>%
  left_join(closs_obs_cf, by = c("project", "period_target")) %>%
  left_join(closs_obs_p, by = c("project", "period_target")) %>%
  left_join(observed_add, by = c("project", "period_target")) %>%
  dplyr::select(!starts_with("ci_")) %>%
  rename(closs_obs_cf = rate_obs.x, closs_obs_p = rate_obs.y, add_obs = additionality)

write.csv(forecast_all, paste0(out_path, "_forecast.csv"), row.names = F)

forecast_all = read.csv(paste0(out_path, "_forecast.csv"), header = T)


#Plot Figure 5. ----
#Overall forecasting performances (mean and range of r2, MAPE and MPB) for each type of forecasts across all target periods

# Summarise forecasting performance for observed counterfactual carbon loss
forecast_summ_closs_cf = forecast_all %>%
  group_by(period_hist_prj, period_hist_reg, period_target, type) %>%
  summarise(r2 = cor(forecast, closs_obs_cf, use = "complete.obs") ^ 2,
            mape = MAPE(forecast, closs_obs_cf),
            mpb = MPB(forecast, closs_obs_cf)) %>%
  ungroup()

write.csv(forecast_summ_closs_cf, paste0(out_path, "_forecast_summary_closs_cf.csv"), row.names = F)
forecast_summ_closs_cf = read.csv(paste0(out_path, "_forecast_summary_closs_cf.csv"), header = T)


figure5_list = vector("list", 0)
for(var in c("r2", "mape", "mpb")) {
  figtitle = switch(var,
                    "r2" = expression("A. Squared correlation coefficient"),
                    "mape" = expression("B. Mean absolute percentage error (MAPE)"),
                    "mpb" = expression("C. Mean percentage bias (MPB)"))
  y_scale = switch(var,
             "r2" = seq(0, 0.75, 0.25),
             "mape" = seq(0, 350, 50),
             "mpb" = seq(-100, 300, 100))
  y_label = switch(var,
             "r2" = expression(R^2),
             "mape" = expression(`MAPE (%)`),
             "mpb" = expression(`MPB (%)`))

  forecast_summ_plot = forecast_summ_closs_cf %>%
    dplyr::select(any_of(c("type", var, "period_target"))) %>%
    group_by(type, period_target) %>%
    summarise(mean = mean(.data[[var]], na.rm = T),
              min = min(.data[[var]], na.rm = T),
              max = max(.data[[var]], na.rm = T),
              lower = quantile(.data[[var]], 0.025, na.rm = T),
              upper = quantile(.data[[var]], 0.975, na.rm = T)) %>%
    ungroup() %>%
    mutate(type = factor(type, levels = c("Project", "Region", "Mixed")))

  figure5_list[[var]] = ggplot(data = forecast_summ_plot, aes(x = period_target, y = mean)) +
    geom_line(aes(color = type), linewidth = 2) +
    geom_ribbon(aes(ymin = lower, ymax = upper, fill = type), alpha = 0.1) +
    scale_color_manual(values = c("#40B0A6", "#CDAC60", "#9467BD")) +
    scale_fill_manual(values = c("#40B0A6", "#CDAC60", "#9467BD")) +
    scale_x_continuous(breaks = 1:10, labels = 1:10) +
    scale_y_continuous(breaks = y_scale, labels = y_scale) +
    labs(title = figtitle, x = "Number of years afte project start", y = y_label,
         color = "Forecast type", fill = "Forecast type") +
    theme_bw() +
    theme(panel.grid = element_blank(),
          plot.title = element_text(size = 28, hjust = 0.5),
          axis.title = element_text(size = 26),
          axis.text = element_text(size = 24),
          axis.ticks = element_line(linewidth = 1),
          axis.ticks.length = unit(0.2, "cm"),
          legend.title = element_text(size = 26),
          legend.text = element_text(size = 24),
          legend.key.size = unit(1.5, "cm"))
}

figure5_full = figure5_list[[1]] / figure5_list[[2]] / figure5_list[[3]] +
  plot_layout(guide = "collect", axes = "collect", axis_titles = "collect") &
  theme(legend.position = "bottom")
ggsave(paste0(fig_path, "figure5_overall_predictive_performance.png"), width = 40, height = 60, unit = "cm")


#Determine the best forecasts using overall rankings of r2, MAPE and MPB for 5-year and 10-year forecasts
forecast_summ_closs_cf_5 = forecast_summ_closs_cf %>%
  filter(period_target == 5) %>%
  mutate(r2_rank = rank(-r2, na.last = NA), mape_rank = rank(mape, na.last = NA), mpb_rank = rank(abs(mpb), na.last = NA))
forecast_summ_closs_cf_10 = forecast_summ_closs_cf %>%
  filter(period_target == 10) %>%
  mutate(r2_rank = rank(-r2, na.last = NA), mape_rank = rank(mape, na.last = NA), mpb_rank = rank(abs(mpb), na.last = NA))
forecast_summ_closs_cf_rank = bind_rows(forecast_summ_closs_cf_5, forecast_summ_closs_cf_10) %>%
  pivot_wider(names_from = period_target,
              values_from = c(r2, mape, mpb, r2_rank, mape_rank, mpb_rank),
              names_sep = "_") %>%
  mutate(sum_rank = r2_rank_5 + mape_rank_5 + mpb_rank_5 + r2_rank_10 + mape_rank_10 + mpb_rank_10)
filter(forecast_summ_closs_cf_rank, sum_rank <= quantile(sum_rank, 0.1, na.rm = T))
#best forecast: mixed with project_used = -10 and region_used = -7

table_1 = forecast_summ_closs_cf_rank %>%
  filter(sum_rank <= quantile(sum_rank, 0.1, na.rm = T)) %>%
  dplyr::select(period_hist_prj, period_hist_reg, type, r2_5, r2_10, mape_5, mape_10, mpb_5, mpb_10, sum_rank) %>%
  arrange(sum_rank)
write.csv(table_1, paste0(fig_path, "table_1.csv"), row.names = F)


#Compile data for model prediction ----
envir_var = project_var %>%
  dplyr::select(!c(country, t0, code) & !starts_with(c("cdens", "n_", "se_")))
envir_var_cor = cor(envir_var %>% dplyr::select(!ID))
corrplot(envir_var_cor, type = "lower", order = "hclust", addCoef.col = "black", diag = F)
#prj_ and reg_ environmental variables highly correlated: remove reg_
#slope and elevation highly correlated: remove elevation

envir_var = project_var %>%
  dplyr::select(!c(country, t0, code, prj_elev) & !starts_with(c("cdens", "n_", "se_", "reg_")))
envir_var_cor = cor(envir_var %>% dplyr::select(!ID))
corrplot(envir_var_cor, type = "lower", order = "hclust", addCoef.col = "black", diag = F)

best_forecast_var = forecast_all %>%
  filter(period_hist_prj == -10 & period_hist_reg == -7 & period_target %in% c(5, 10)) %>%
  dplyr::select(!c(period_hist_prj, period_hist_reg, type)) %>%
  pivot_wider(names_from = period_target, values_from = c(forecast, closs_obs_cf, closs_obs_p, add_obs))

model_df = left_join(best_forecast_var, envir_var, join_by(project == ID)) %>%
  left_join(observed_var, ., join_by(project == project)) %>%
  left_join(observed_add_var, ., join_by(project == project))
model_df_scaled = model_df %>%
  mutate(across(-c(project, matches("(_5|_10)$")), ~ as.numeric(scale(.)))) #scale and center all predictor columns except project
write.csv(model_df_scaled, paste0(fig_path, "model_df_scaled.csv"), row.names = F)

model_df_scaled = read.csv(paste0(fig_path, "model_df_scaled.csv"), header = T)


#Plot Figure 6. ----
#Observed vs predicted counterfactual carbon loss for 5-year and 10-year forecasts
plot_cf_5 = PlotModel(yr = 5, type = "cf")
plot_cf_10 = PlotModel(yr = 10, type = "cf")

plot_cf_panel = plot_cf_5$plot + plot_cf_10$plot +
  plot_layout(axes = "collect", axis_titles = "collect")
title_y = wrap_elements(grid::textGrob(paste("Observed annual counterfactual carbon loss (%)"),
                                       rot = 90, gp = gpar(fontsize = 28)))
plot_cf_all = title_y + plot_cf_panel +
  plot_layout(width = c(0.02, 1))
ggsave(paste0(fig_path, "figure6_closs_cf_observed_vs_forecasted.png"), width = 60, height = 30, unit = "cm")


#Plot Figure 7. ----
#Linear model predicting observed project carbon loss for 5-year and 10-year intervals
plot_p_full_5 = PlotModel(yr = 5, type = "p", model = "full")
plot_p_full_10 = PlotModel(yr = 10, type = "p", model = "full")
plot_p_naive_5 = PlotModel(yr = 5, type = "p", model = "naive")
plot_p_naive_10 = PlotModel(yr = 10, type = "p", model = "naive")
plot_p_sel_5 = PlotModel(yr = 5, type = "p", model = "sel")
plot_p_sel_10 = PlotModel(yr = 10, type = "p", model = "sel")

plot_p_full = plot_p_full_5$plot + plot_p_full_10$plot +
  plot_layout(axes = "collect", axis_titles = "collect")
plot_p_full_title = wrap_elements(grid::textGrob("A. Full model", gp = gpar(fontsize = 36, fontface = "bold")))
plot_p_naive = plot_p_naive_5$plot + plot_p_naive_10$plot +
  plot_layout(axes = "collect", axis_titles = "collect")
plot_p_naive_title = wrap_elements(grid::textGrob("B. Naive model", gp = gpar(fontsize = 36, fontface = "bold")))
plot_p_sel = plot_p_sel_5$plot + plot_p_sel_10$plot +
  plot_layout(axes = "collect", axis_titles = "collect")
plot_p_sel_title = wrap_elements(grid::textGrob("C. Selected model", gp = gpar(fontsize = 36, fontface = "bold")))

plot_p_stack = plot_p_full_title / plot_p_full / plot_p_naive_title / plot_p_naive / plot_p_sel_title / plot_p_sel +
  plot_layout(height = c(0.15, 1, 0.15, 1, 0.15, 1))
title_y = wrap_elements(grid::textGrob(paste("Observed annual project carbon loss (%)"),
                                       rot = 90, gp = gpar(fontsize = 28)))
plot_p_all = title_y + plot_p_stack +
  plot_layout(width = c(0.02, 1))
plot_p_all
ggsave(paste0(fig_path, "figure7_closs_p_observed_vs_forecasted.png"), width = 60, height = 60, unit = "cm")


#Plot Figure 8. ----
#Linear model predicting observed carbon credit production for 5-year and 10-year intervals
plot_add_full_5 = PlotModel(yr = 5, type = "add", model = "full")
plot_add_full_10 = PlotModel(yr = 10, type = "add", model = "full")
plot_add_naive_5 = PlotModel(yr = 5, type = "add", model = "naive")
plot_add_naive_10 = PlotModel(yr = 10, type = "add", model = "naive")
plot_add_sel_5 = PlotModel(yr = 5, type = "add", model = "sel")
plot_add_sel_10 = PlotModel(yr = 10, type = "add", model = "sel")

plot_add_full = plot_add_full_5$plot + plot_add_full_10$plot +
  plot_layout(axes = "collect", axis_titles = "collect")
plot_add_full_title = wrap_elements(grid::textGrob("A. Full model", gp = gpar(fontsize = 36, fontface = "bold")))
plot_add_naive = plot_add_naive_5$plot + plot_add_naive_10$plot +
  plot_layout(axes = "collect", axis_titles = "collect")
plot_add_naive_title = wrap_elements(grid::textGrob("B. Naive model", gp = gpar(fontsize = 36, fontface = "bold")))
plot_add_sel = plot_add_sel_5$plot + plot_add_sel_10$plot +
  plot_layout(axes = "collect", axis_titles = "collect")
plot_add_sel_title = wrap_elements(grid::textGrob("C. Selected model", gp = gpar(fontsize = 36, fontface = "bold")))

plot_add_stack = plot_add_full_title / plot_add_full / plot_add_naive_title / plot_add_naive / plot_add_sel_title / plot_add_sel +
  plot_layout(height = c(0.15, 1, 0.15, 1, 0.15, 1))
title_y = wrap_elements(grid::textGrob(bquote(paste("Observed annual carbon credit production (MgC ", ha^-1, " ", yr^-1, ")")),
                                       rot = 90, gp = gpar(fontsize = 28)))
plot_add_all = title_y + plot_add_stack +
  plot_layout(width = c(0.02, 1))
plot_add_all
ggsave(paste0(fig_path, "figure8_additionality_observed_vs_forecasted.png"), width = 60, height = 60, unit = "cm")