rm(list = ls())

#Load packages
library(tidyverse) #ggplot2, dplyr, and stringr used in plotPlacebo/plotBaseline.r: tibble to store labels with bquote()
library(magrittr) #pipe operators
library(parallel) #detectCores()
library(future) #parallelise lapply() : future_lapply()
library(future.apply) #parallelise lapply(): future_lapply()
library(boot) #boot::boot
library(httpgd)
library(mgcv)
library(broom)

#Set parallelise plan
plan(multisession, workers = 20)

#Load pre-defined functions
source("FindFiles.r") #wrapper function to search files or folders based on inclusion/exclusion keywords
source("ReformatPixels.r") #wrapper function to reformat column names of data frame of matched pixels
source("AssessBalance.r") #function to assess matching balance
source("GetCarbonSeries.r") #function to generate time series of annual change in project-level average carbon density
source("BootOut.r")

#Define input variables
project_dir = "/maps/epr26/tmf_pipe_out/" #path to directories containing implementation outputs
out_path = "/maps/epr26/ex_ante_forecast_out/out_ongoing" #path of files generated by this repo, including in forecast_1_setup.r

project_var = read.csv(paste0(out_path, "_project_var.csv"), header = T)

#Read project variables
projects = project_sel$project
t0_vec = project_sel$t0

closs_boot_list = vector("list", length(projects))
for(i in seq_along(projects)) {
  a = Sys.time()
  t0 = t0_vec[i]
  project_i = projects[i]
  closs_obs = read.csv(paste0(out_path, "_closs_obs_cf_", projects[i], ".csv"), header = T)
  closs_hist = read.csv(paste0(out_path, "_closs_project_", projects[i], ".csv"), header = T)
  closs_reg = read.csv(paste0(out_path, "_closs_regional_", projects[i], ".csv"), header = T)

  #calculate annual carbon loss rates
  closs_p_cf = bind_rows(
    closs_hist %>% mutate(src = "hist"),
    closs_obs %>% mutate(src = "obs")) %>%
    arrange(pair, cdens_boot, year, src) %>%
    distinct(pair, cdens_boot, year, .keep_all = T) %>% #remove duplicates
    group_by(pair, cdens_boot) %>%
    mutate(closs_cf_annual = (lag(counterfactual) - counterfactual) / lag(counterfactual),
           closs_p_annual = (lag(project) - project) / lag(project)) %>%
    ungroup()
  closs_reg_ann = closs_reg %>%
    rename(regional = carbon_density) %>%
    group_by(pair, cdens_boot) %>%
    mutate(closs_reg_annual = (lag(regional) - regional) / lag(regional)) %>%
    ungroup()
  
  #merge closs_p_cf and closs_reg_ann, keeping all year-pair-cdens_boot combinations in closs_p_cf
  closs_merge = closs_p_cf %>%
    left_join(closs_reg_ann, by = c("year", "pair", "cdens_boot")) %>%
    select(-src, -treatment, -closs.x, -closs.y) %>%
    filter(!is.na(closs_cf_annual) | !is.na(closs_p_annual) | !is.na(closs_reg_annual))
  
  closs_boot_ann_list = vector("list", length = length(unique(closs_merge$year)))
  for(j in unique(closs_merge$year)) {
    closs_merge_j = filter(closs_merge, year == j) 
    closs_cf_boot = boot::boot(data = closs_merge_j,
                               statistic = function(dat, ind) mean(dat[ind, ]$closs_cf_annual, na.rm = T),
                               R = 1000)$t
    closs_p_boot = boot::boot(data = closs_merge_j,
                              statistic = function(dat, ind) mean(dat[ind, ]$closs_p_annual, na.rm = T),
                              R = 1000)$t
    closs_reg_boot = boot::boot(data = closs_merge_j,
                                statistic = function(dat, ind) mean(dat[ind, ]$closs_reg_annual, na.rm = T),
                                R = 1000)$t

    closs_boot_ann_list[[j]] = data.frame(year = j,
                                      closs_cf_annual = closs_cf_boot,
                                      closs_p_annual = closs_p_boot,
                                      closs_reg_annual = closs_reg_boot)
  }
  closs_boot_i = list_rbind(closs_boot_ann_list)
  write.csv(closs_boot_i, paste0(out_path, "closs_annual_", project_i, ".csv"), row.names = F)
  closs_boot_list[[i]] = closs_boot_i
  b = Sys.time()
  cat("Project", i, "/", length(projects), "-", projects[i], "- plot carbon loss rates :", format(difftime(b, a, units = "secs")), "\n")
}

for(i in seq_along(projects)) {
  a = Sys.time()
  t0 = t0_vec[i]
  project_i = projects[i]

  closs_long = closs_boot_list[[i]] %>%
    pivot_longer(cols = c(closs_cf_annual, closs_p_annual, closs_reg_annual),
                 names_to = "type",
                 values_to = "closs_annual") %>%
    mutate(type = case_when(
      type == "closs_cf_annual" ~ "Counterfactual",
      type == "closs_p_annual" ~ "Project",
      type == "closs_reg_annual" ~ "Regional"
    )) %>%
    mutate(
      project = project_i,
      year_c = year - t0,
      year_post = pmax(0, year_c)
    )

  coef_df = closs_long %>%
    group_by(type) %>%
    group_modify(~ {
      gam(
        closs_annual ~ year_c + year_post,
        data = .x,
        method = "REML"
      ) |>
        tidy(parametric = TRUE)
    }) %>%
    filter(term %in% c("(Intercept)", "year_c", "year_post")) %>%
    select(type, term, estimate) %>%
    tidyr::pivot_wider(names_from = term, values_from = estimate) %>%
    mutate(
      intercept_at_t0 = `(Intercept)`,
      slope_pre  = year_c,
      slope_post = year_c + year_post
    ) %>%
    select(type, intercept_at_t0, slope_pre, slope_post)

  closs_long_mean = closs_long %>%
    group_by(year, type) %>%
    summarise(closs_annual = mean(closs_annual)) %>%
    ungroup()

  closs_plot_i = closs_long_mean %>%
    left_join(coef_df, by = "type") %>%
    mutate(
      fitted = ifelse(
        year < t0,
        intercept_at_t0 + slope_pre  * (year - t0),
        intercept_at_t0 + slope_post * (year - t0))
    ) %>%
    mutate(
      fitted = ifelse(type == "Regional" & year >= t0, NA, fitted),
      project = project_i
    )
  write.csv(closs_plot_i, paste0(out_path, "closs_annual_plot_", project_i, ".csv"), row.names = F)

  closs_plot_list[[i]] = closs_plot_i
  b = Sys.time()
  cat("Project", i, "/", length(projects), "-", projects[i], "- plot carbon loss rates :", format(difftime(b, a, units = "secs")), "\n")
}

closs_plot = list_rbind(closs_plot_list)

p = ggplot(data = closs_plot, aes(x = year)) +
  geom_point(aes(y = closs_annual, color = type), na.rm = T) +
  geom_line(aes(y = fitted, color = type), linewidth = 1.2, na.rm = T) +
  geom_vline(xintercept = t0, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  facet_wrap_paginate(~project, ncol = 3, nrow = 3, page = 1) +
  scale_color_manual(values = c("darkred", "blue", "green"),
                      labels = c("Counterfactual", "Project", "Regional"),
                      name = "Carbon loss rate") +
  labs(title = paste0("Project ", project_i, " annual carbon loss rates"),
        x = "Year",
        y = "Annual carbon loss rate (%)") +
  theme_minimal()

n_pages = n_pages(p)

for (i in seq_len(n_pages)) {
  ggsave(
    filename = paste0(out_path, "_closs_plot_page_", sprintf("%02d", i), ".png"),
    plot = p + facet_wrap_paginate(
      ~project, ncol = 3, nrow = 3, page = i
    ),
    width = 8, height = 6, units = "in", dpi = 300
  )
}