# This script reads the bootstrapped mean of:
# 1. Ex post additionality (boot_additionality_[proj].csv)
# 2. Historical project carbon loss rate (boot_project_closs_rate_[proj].csv)
# 3. Historical regional carbon loss rates (boot_regional_closs_rate_[proj].csv)
# generates simple project-based and region-based forecasts as well as mixed forecasts using different historical periods,
# and compares and visualises their performance over different target periods

# It requires the following input variables:
#1. out_path: absolute path (plus prefix) of files generated by this repo, including in forecast_1_setup.r
#2. fig_path: absolute path (plus prefix) of the output figures


# Setup ----
rm(list = ls())

#Load packages
library(tidyverse)
library(magrittr) #pipe operators
library(corrplot) #corrplot::corrplot
library(MASS) #MASS::stepAIC
library(effectsize) #effectsize::eta_squared
library(patchwork)
library(grid) #grid::textGrob, grid::gpar
library(httpgd)

#Read in custom functions
source("PlotModel.r")

GOF = function(forecast, observed) {
  return(1 - sum((observed - forecast) ^ 2, na.rm = T) / sum((observed - mean(observed, na.rm = T)) ^ 2, na.rm = T))
}
MAE = function(forecast, observed) {
  return(mean(abs(forecast - observed), na.rm = T))
}
RMSE = function(forecast, observed) {
  return(sqrt(mean((forecast - observed) ^ 2, na.rm = T)))
}

#Define input variables
out_path = "/maps/epr26/ex_ante_forecast_out/out_ongoing" #path of files generated by this repo
fig_path = "/maps/epr26/ex_ante_forecast_out/out_" #path of output figures

project_var = read.csv(paste0(out_path, "_project_var.csv"), header = T)
projects = project_var$project
t0_vec = project_var$t0
area_ha_vec = project_var$area_ha
cdens_list = project_var %>%
  dplyr::select(project, cdens_1:cdens_6) %>%
  pivot_longer(cdens_1:cdens_6, names_to = "land.use.class", names_prefix = "cdens_", values_to = "carbon.density") %>%
  split(f = .$project)


# Load and format data ----

#Load boostrapped data
boot_add = read.csv(paste0(out_path, "_boot_additionality_arith.csv"), header = T)
boot_closs_obs_cf = read.csv(paste0(out_path, "_boot_closs_obs_cf.csv"), header = T)
boot_closs_obs_p = read.csv(paste0(out_path, "_boot_closs_obs_p.csv"), header = T)
boot_closs_project = read.csv(paste0(out_path, "_boot_closs_project.csv"), header = T)
boot_closs_region = read.csv(paste0(out_path, "_boot_closs_regional.csv"), header = T)

#Express them as relative to project start
boot_add_list = vector("list", length(projects))
boot_closs_obs_cf_list = vector("list", length(projects))
boot_closs_obs_p_list = vector("list", length(projects))
boot_closs_project_list = vector("list", length(projects))
boot_closs_region_list = vector("list", length(projects))

for(i in seq_along(projects)) {
  t0 = t0_vec[i]
  project_i = projects[i]
  boot_add_list[[i]] = boot_add %>%
      filter(project == project_i) %>%
      mutate(year = year - t0)
  boot_closs_obs_cf_list[[i]] = boot_closs_obs_cf %>%
      filter(project == project_i) %>%
      mutate(year = year - t0)
  boot_closs_obs_p_list[[i]] = boot_closs_obs_p %>%
      filter(project == project_i) %>%
      mutate(year = year - t0)
  boot_closs_project_list[[i]] = boot_closs_project %>%
      filter(project == project_i) %>%
      mutate(year = year - t0)
  boot_closs_region_list[[i]] = boot_closs_region %>%
      filter(project == project_i) %>%
      mutate(year = year - t0)
}

boot_add_rel = list_rbind(boot_add_list)
boot_closs_obs_cf_rel = list_rbind(boot_closs_obs_cf_list)
boot_closs_obs_p_rel = list_rbind(boot_closs_obs_p_list)
boot_closs_project_rel = list_rbind(boot_closs_project_list)
boot_closs_region_rel = list_rbind(boot_closs_region_list)

#Reformat observed counterfactual carbon loss data to consistently be 10 years in length for every project
closs_obs_cf = boot_closs_obs_cf_rel %>%
  filter(year <= 10) %>%
  rename(period_target = year, rate_obs = mean) %>%
  complete(project, period_target = 1:10, fill = list(rate_obs = NA_real_))

closs_obs_p = boot_closs_obs_p_rel %>%
  filter(year <= 10) %>%
  rename(period_target = year, rate_obs = mean) %>%
  complete(project, period_target = 1:10, fill = list(rate_obs = NA_real_))

observed_add = boot_add_rel %>%
  filter(year <= 10) %>%
  rename(period_target = year, additionality = mean) %>%
  complete(project, period_target = 1:10, fill = list(additionality = NA_real_))

# Generate forecasts ----

#Generate project- or region-based forecasts
forecast_prj_list = vector("list", 10 * length(projects))
forecast_reg_list = vector("list", 10 * length(projects))
for(i in 1:10) {
  yr_i = i - 11
  for(k in seq_along(projects)) {
    project_k = projects[k]
    ind = (i - 1) * length(projects) + k

    #project-based forecasts
    rate_project = boot_closs_project_rel %>%
      filter(year == yr_i & project == project_k) %>%
      pull(mean)
    forecast_prj_list[[ind]] = data.frame(period_hist_prj = yr_i, period_hist_reg = NA, period_target = 1:10,
                                          forecast = rate_project, project = project_k)

    #region-based forecasts
    rate_region = boot_closs_region_rel %>%
      filter(year == yr_i & project == project_k) %>%
      pull(mean)
    forecast_reg_list[[ind]] = data.frame(period_hist_prj = NA, period_hist_reg = yr_i, period_target = 1:10,
                                          forecast = rate_region, project = project_k)
  }
}
forecast_prj = list_rbind(forecast_prj_list) %>%
  mutate(type = "Project")
forecast_reg = list_rbind(forecast_reg_list) %>%
  mutate(type = "Region")

#Generate mixed forecasts
forecast_mix_list = vector("list", 10 * 10 * length(projects))
for(i in 1:10) {
  yr_i = i - 11
  for(j in 1:10) {
    yr_j = j - 11
    for(k in seq_along(projects)) {
      project_k = projects[k]
      ind = (i - 1) * 10 * length(projects) + (j - 1) * length(projects) + k

      rate_project = boot_closs_project_rel %>%
        filter(year == yr_i & project == project_k) %>%
        pull(mean)
      rate_region = boot_closs_region_rel %>%
        filter(year == yr_j & project == project_k) %>%
        pull(mean)
      rate_mixed = ((rate_project ^ (9:0)) * (rate_region ^ (0:9))) ^ (1 / 10) #weighted geometric mean
      forecast_mix_list[[ind]] = data.frame(period_hist_prj = yr_i, period_hist_reg = yr_j, period_target = 1:10,
                                            forecast = rate_mixed, project = project_k)
    }
  }
}
forecast_mix = list_rbind(forecast_mix_list) %>%
  mutate(type = "Mixed")

#Merge forecasted and observed values
forecast_all = bind_rows(forecast_prj, forecast_reg, forecast_mix) %>%
  left_join(closs_obs_cf, by = c("project", "period_target")) %>%
  left_join(closs_obs_p, by = c("project", "period_target")) %>%
  left_join(observed_add, by = c("project", "period_target")) %>%
  dplyr::select(!starts_with("ci_")) %>%
  rename(closs_obs_cf = rate_obs.x, closs_obs_p = rate_obs.y, add_obs = additionality)

write.csv(forecast_all, paste0(out_path, "_forecast.csv"), row.names = F)
forecast_all = read.csv(paste0(out_path, "_forecast.csv"), header = T)


# Calculate forecast performance ----
FitPerformance = function(x, y) {
  dat_in = data.frame(forecast = x, observed = y)
  mod = lm(observed ~ forecast, data = dat_in)
  dat = data.frame(pred = predict(mod),
                   obs = mod$model$observed)
  gof = GOF(dat$pred, dat$obs) #goodness-of-fit (R2 over 1:1 line)
  mae = MAE(dat$pred, dat$obs) #mean absolute percentage error (MAPE)
  rmse = RMSE(dat$pred, dat$obs) #mean percentage bias (MPB)
  return(list(GOF = gof, MAE = mae, RMSE = rmse))
}

forecast_summ = forecast_all %>%
  group_by(period_hist_prj, period_hist_reg, period_target, type) %>%
  summarise(gof = FitPerformance(forecast * 100, closs_obs_cf * 100)$GOF, #turn into percentage
            mae = FitPerformance(forecast * 100, closs_obs_cf * 100)$MAE,
            rmse = FitPerformance(forecast * 100, closs_obs_cf * 100)$RMSE) %>%
  ungroup()

write.csv(forecast_summ, paste0(out_path, "_forecast_summary.csv"), row.names = F)
forecast_summ = read.csv(paste0(out_path, "_forecast_summary.csv"), header = T)


# Plot Figure 5. Overall forecasting performances for each type of forecasts across all target periods ----
metrics_name = c("gof", "mae", "rmse")
figure5_list = vector("list", 0)
for(var in metrics_name) {
  figtitle = switch(var,
                    "gof" = expression(paste("A. Goodness-of-fit (", R^2, ")")),
                    "mae" = expression("B. Mean absolute error (MAE)"),
                    "rmse" = expression("C. Root mean square error (RMSE)"))
  y_limit = switch(var,
             "gof" = c(0, 0.75),
             "mae" = c(0, 1.25),
             "rmse" = c(0, 2))
  y_scale = switch(var,
             "gof" = seq(0, 0.75, 0.25),
             "mae" = seq(0, 1.25, 0.25),
             "rmse" = seq(0, 2, 0.5))
  y_label = switch(var,
             "gof" = "Goodness-of-fit",
             "mae" = "MAE",
             "rmse" = "RMSE")

  forecast_summ_plot = forecast_summ %>%
    dplyr::select(any_of(c("type", var, "period_target"))) %>%
    group_by(type, period_target) %>%
    summarise(mean = mean(.data[[var]], na.rm = T),
              sd = mean(.data[[var]], na.rm = T),
              lower = quantile(.data[[var]], 0.025, na.rm = T),
              upper = quantile(.data[[var]], 0.975, na.rm = T)) %>%
    ungroup() %>%
    mutate(se = sd / sqrt(ifelse(type == "Mixed", 100, 10)),
           se_l = mean - se,
           se_u = mean + se) %>%
    mutate(type = factor(type, levels = c("Project", "Region", "Mixed")))

  figure5_list[[var]] = ggplot(data = forecast_summ_plot, aes(x = period_target, y = mean)) +
    geom_line(aes(color = type), linewidth = 2) +
    geom_ribbon(aes(ymin = se_l, ymax = se_u, fill = type), alpha = 0.1) +
    scale_color_manual(values = c("#40B0A6", "#CDAC60", "#9467BD")) +
    scale_fill_manual(values = c("#40B0A6", "#CDAC60", "#9467BD")) +
    scale_x_continuous(breaks = 1:10, labels = 1:10) +
    scale_y_continuous(limit = y_limit, breaks = y_scale, labels = y_scale) +
    labs(title = figtitle, x = "Number of years after project start", y = y_label,
         color = "Forecast type", fill = "Forecast type") +
    theme_bw() +
    theme(panel.grid = element_blank(),
          plot.title = element_text(size = 28, hjust = 0.5),
          axis.title = element_text(size = 26),
          axis.text = element_text(size = 24),
#          axis.text.y = element_text(margin = margin(r = 5)),
          axis.ticks = element_line(linewidth = 1),
          axis.ticks.length = unit(0.2, "cm"),
          legend.title = element_text(size = 26),
          legend.text = element_text(size = 24),
          legend.key.size = unit(1.5, "cm"))
  if(var == "mpb") {
    figure5_list[[var]] = figure5_list[[var]] +
      geom_hline(yintercept = 0, linetype = "dashed")
  }
}

figure5_full = figure5_list[[1]] / figure5_list[[2]] / figure5_list[[3]] +
  plot_layout(guide = "collect", axes = "collect", axis_titles = "collect") &
  theme(legend.position = "bottom")
ggsave(paste0(fig_path, "figure_5_overall_forecast_performance.png"), width = 40, height = 60, unit = "cm")


#Plot Figure S3. Overall forecasting performances for project/region-based forecasts across historical periods --------
#@@@


#Plot Figure S4. Overall forecasting performances for mixed forecasts across all combinations of historical periods --------
#@@@


# Determine the best forecasts ----

#Calculate rankings of r2, MAE and RMSE for 5-year and 10-year target periods
forecast_rank_5 = forecast_summ %>%
  filter(period_target == 5) %>%
  mutate(gof_rank = rank(-gof, na.last = NA),
         mae_rank = rank(mae, na.last = NA),
         rmse_rank = rank(abs(rmse), na.last = NA)) %>%
  mutate(sum_rank = gof_rank + mae_rank + rmse_rank)

forecast_rank_10 = forecast_summ %>%
  filter(period_target == 10) %>%
  mutate(gof_rank = rank(-gof, na.last = NA),
         mae_rank = rank(mae, na.last = NA),
         rmse_rank = rank(abs(rmse), na.last = NA)) %>%
  mutate(sum_rank = gof_rank + mae_rank + rmse_rank)

forecast_rank = bind_rows(forecast_rank_5, forecast_rank_10) %>%
  pivot_wider(names_from = period_target,
              values_from = c(gof, mae, rmse, gof_rank, mae_rank, rmse_rank, sum_rank),
              names_sep = "_")

#Sort by total ranking and retain the best 10% forecasts
best_5 = forecast_rank %>%
  filter(sum_rank_5 <= quantile(sum_rank_5, 0.1, na.rm = T)) %>%
  dplyr::select(type, period_hist_prj, period_hist_reg, gof_5, mae_5, rmse_5, sum_rank_5) %>%
  arrange(sum_rank_5)
best_10 = forecast_rank %>%
  filter(sum_rank_10 <= quantile(sum_rank_10, 0.1, na.rm = T)) %>%
  dplyr::select(type, period_hist_prj, period_hist_reg, gof_10, mae_10, rmse_10, sum_rank_10) %>%
  arrange(sum_rank_10)

write.csv(best_5, paste0(fig_path, "table_s3a_best_5.csv"), row.names = F)
write.csv(best_10, paste0(fig_path, "table_s3b_best_10.csv"), row.names = F)


# Compile data for model prediction ----
envir_var = project_var %>%
  dplyr::select(!c(country, t0) & !starts_with(c("cdens", "n_", "se_", "reg_")))
#project-wide and regional environmental variables highly correlated: remove regional variables

#initial carbon stock
c_init_var = lapply(seq_along(projects), function(i) {
  t0 = t0_vec[i]
  add_i = read.csv(paste0(out_path, "_additionality_", projects[i], ".csv"), header = T)
  c_init_i = mean(subset(add_i, year == t0)$project, na.rm = T)
  c_init_df = data.frame(project = projects[i], c_init = c_init_i)
  return(c_init_df)
}) %>%
  list_rbind()

#best 5-year forecast: mixed forecast using project = -8 and region = -2
forecast_obs_5_var = forecast_all %>%
  filter(period_hist_prj == -8 & period_hist_reg == -2 & period_target == 5) %>%
  dplyr::select(!c(period_hist_prj, period_hist_reg, type)) %>%
  pivot_wider(names_from = period_target, values_from = c(forecast, closs_obs_cf, closs_obs_p, add_obs))

#best 10-year forecast: region-based forecast using region = -7
forecast_obs_10_var = forecast_all %>%
  filter(is.na(period_hist_prj) & period_hist_reg == -7 & period_target == 10) %>%
  dplyr::select(!c(period_hist_prj, period_hist_reg, type)) %>%
  pivot_wider(names_from = period_target, values_from = c(forecast, closs_obs_cf, closs_obs_p, add_obs))

model_df = list(envir_var, c_init_var, forecast_obs_5_var, forecast_obs_10_var) %>% reduce(left_join, by = "project") %>%
  mutate(add_rate_5 = closs_obs_cf_5 - closs_obs_p_5,
         add_rate_10 = closs_obs_cf_10 - closs_obs_p_10,
         credit_5 = c_init * ((1 - closs_obs_p_5) ^ 5) - c_init * ((1 - closs_obs_cf_5) ^ 5))
write.csv(model_df, paste0(fig_path, "model_df.csv"), row.names = F)
model_df = read.csv(paste0(fig_path, "model_df.csv"), header = T)

#plot correlation matrix
envir_var_cor = model_df %>%
  rename(Area = area_ha,
         "Mean elevation" = prj_elev,
         "Mean slope" = prj_slope,
         "Mean remoteness" = prj_remote,
         "Mean GDP per capita" = gdppc_mean,
         "GDP per capita growth rate" = gdppc_rate,
         "Corruption index" = wgicc_mean,
         "Initial carbon density" = c_init,
         "Forecasted counterfactual loss rate" = forecast_5) %>%
  dplyr::select(!c(project) & !ends_with(c("_5", "_10"))) %>%
  cor()
png(paste0(fig_path, "figure_s3_envir_var_corr.png"), width = 20, height = 20, unit = "cm", res = 300)
corrplot(envir_var_cor, type = "lower", order = "hclust", addCoef.col = "black", diag = F)
dev.off()

#remove the 27th project and collinear variables
model_df_trimmed = model_df[1:26, ]

#scale and center all predictor columns
var_to_scale = c("area_ha", "prj_slope", "prj_remote", "gdppc_mean", "gdppc_rate", "wgicc_mean", "forecast_5", "forecast_10")
model_df_scaled = model_df_trimmed %>%
  mutate(across(all_of(var_to_scale), ~ as.numeric(scale(.x))))
write.csv(model_df_scaled, paste0(fig_path, "model_df_scaled.csv"), row.names = F)

# Predictive models ----

#Counterfactual carbon loss: naive model (only forecast is used)
plot_cf = PlotModel(input = model_df_trimmed, yr = 5, obs_var = "closs_obs_cf", model = "naive")

#Project carbon loss: model selection
plot_p = PlotModel(input = model_df_trimmed, yr = 5, obs_var = "closs_obs_p", model = "sel")

#Difference in carbon loss: model selection
plot_reduc = PlotModel(input = model_df_trimmed, yr = 5, obs_var = "add_rate", model = "forecast")

#Carbon credit production (emissions reductions): model selection
plot_credit = PlotModel(input = model_df_trimmed, yr = 5, obs_var = "credit", model = "sel")

#Harmonise predictive models by using any selected variables across models
retained_var = union(names(plot_p$model$coefficients)[-1],
                     names(plot_credit$model$coefficients)[-1])

plot_p_uni = PlotModel(input = model_df_trimmed, yr = 5, obs_var = "closs_obs_p", model = retained_var)
plot_credit_uni = PlotModel(input = model_df_trimmed, yr = 5, obs_var = "credit", model = retained_var)

#Get model diagnostics
png(paste0(fig_path, "figure_s_diagnostic_p.png"), width = 600, height = 600)
par(mfrow = c(2, 2))
plot(plot_p_uni$model)
dev.off()

png(paste0(fig_path, "figure_s_diagnostic_credit.png"), width = 600, height = 600)
par(mfrow = c(2, 2))
plot(plot_credit_uni$model)
dev.off()

#Get model summary
summary(plot_p_uni$model)
eta_squared(plot_p_uni$model, partial = T)
summary(plot_credit_uni$model)
eta_squared(plot_credit_uni$model, partial = T)


# Plot Figure 6. Forecasting vs observed for the 5-year period ----
plot_fig6l = plot_cf$plot / plot_p$plot / plot_reduc$plot +
  plot_layout(guide = "collect", axes = "collect", axis_titles = "collect", heights = c(1, 1, 1))

plot_fig6r = plot_spacer() / plot_credit$plot / plot_spacer() +
  plot_layout(heights = c(1.125, 1.1, 0.775))
plot_fig6 = plot_fig6l | plot_fig6r +
  plot_layout(widths = c(1, 1))

ggsave(paste0(fig_path, "figure_6_obs_pred_new.png"), plot = plot_fig6, width = 60, height = 60, unit = "cm")
