rm(list = ls())

#Load packages
library(tidyverse) #ggplot2, dplyr, and stringr
library(magrittr) #pipe operators
library(future) #parallelise lapply(): future_lapply()
library(future.apply) #parallelise lapply(): future_lapply()
library(boot) #boot::boot
library(mgcv) #mgcv::gam
library(broom) #broom::tidy

#Load pre-defined functions
source("FindFiles.r") #wrapper function to search files or folders based on inclusion/exclusion keywords
source("ReformatPixels.r") #wrapper function to reformat column names of data frame of matched pixels
source("AssessBalance.r") #function to assess matching balance
source("GetCarbonSeries.r") #function to generate time series of annual change in project-level average carbon density
source("BootOut.r")

#Define input variables
in_path = "../03_Project_forecasting/supporting_data/" #path of files where input files are to be read from
out_path = "../03_Project_forecasting/" #path where files generated by this script will be saved to
fig_path = "../03_Project_forecasting/manuscript/" #path where files generated by this script will be saved to

project_var = read.csv(paste0(in_path, "project_var.csv"), header = T)

#Read project variables
projects = project_var$project
t0_vec = project_var$t0

#Calculate annual carbon loss rates with bootstrapping
closs_boot_list = vector("list", length(projects))
for(i in seq_along(projects)) {
  a = Sys.time()
  t0 = t0_vec[i]
  project_i = projects[i]
  closs_obs = read.csv(paste0(in_path, "_closs_obs_cf_", projects[i], ".csv"), header = T)
  closs_hist = read.csv(paste0(in_path, "_closs_project_", projects[i], ".csv"), header = T)
  closs_reg = read.csv(paste0(in_path, "_closs_regional_", projects[i], ".csv"), header = T)

  #calculate annual carbon loss rates
  closs_p_cf = bind_rows(
    closs_hist %>% mutate(src = "hist"),
    closs_obs %>% mutate(src = "obs")) %>%
    arrange(pair, cdens_boot, year, src) %>%
    distinct(pair, cdens_boot, year, .keep_all = T) %>% #remove duplicates
    group_by(pair, cdens_boot) %>%
    mutate(closs_cf_annual = (lag(counterfactual) - counterfactual) / lag(counterfactual),
           closs_p_annual = (lag(project) - project) / lag(project)) %>%
    ungroup()
  closs_reg_ann = closs_reg %>%
    rename(regional = carbon_density) %>%
    group_by(pair, cdens_boot) %>%
    mutate(closs_reg_annual = (lag(regional) - regional) / lag(regional)) %>%
    ungroup()
  
  #merge closs_p_cf and closs_reg_ann, keeping all year-pair-cdens_boot combinations in closs_p_cf
  closs_merge = closs_p_cf %>%
    left_join(closs_reg_ann, by = c("year", "pair", "cdens_boot")) %>%
    select(-src, -treatment, -closs.x, -closs.y) %>%
    filter(!is.na(closs_cf_annual) | !is.na(closs_p_annual) | !is.na(closs_reg_annual))
  
  closs_boot_ann_list = vector("list", length = length(unique(closs_merge$year)))
  for(j in unique(closs_merge$year)) {
    closs_merge_j = filter(closs_merge, year == j) 
    closs_cf_boot = boot::boot(data = closs_merge_j,
                               statistic = function(dat, ind) mean(dat[ind, ]$closs_cf_annual, na.rm = T),
                               R = 1000)$t
    closs_p_boot = boot::boot(data = closs_merge_j,
                              statistic = function(dat, ind) mean(dat[ind, ]$closs_p_annual, na.rm = T),
                              R = 1000)$t
    closs_reg_boot = boot::boot(data = closs_merge_j,
                                statistic = function(dat, ind) mean(dat[ind, ]$closs_reg_annual, na.rm = T),
                                R = 1000)$t

    closs_boot_ann_list[[j]] = data.frame(year = j,
                                      closs_cf_annual = closs_cf_boot,
                                      closs_p_annual = closs_p_boot,
                                      closs_reg_annual = closs_reg_boot)
  }
  closs_boot_i = list_rbind(closs_boot_ann_list)
  write.csv(closs_boot_i, paste0(out_path, "_closs_annual_", project_i, ".csv"), row.names = F)
  closs_boot_list[[i]] = closs_boot_i
  b = Sys.time()
  cat("Project", i, "/", length(projects), "-", projects[i], "- plot carbon loss rates :", format(difftime(b, a, units = "secs")), "\n")
}

#Calculate coefficients of GAM models for mean annual carbon loss rates
closs_mean_list = vector("list", length(projects))
closs_plot_list = vector("list", length(projects))
for(i in seq_along(projects)) {
  a = Sys.time()
  t0 = t0_vec[i]
  project_i = projects[i]

  closs_boot_i = read.csv(paste0(out_path, "_closs_annual_", project_i, ".csv"), header = T)
  closs_long = closs_boot_i %>%
    pivot_longer(cols = c(closs_cf_annual, closs_p_annual, closs_reg_annual),
                 names_to = "type",
                 values_to = "closs_annual") %>%
    mutate(type = case_when(
      type == "closs_cf_annual" ~ "Counterfactual",
      type == "closs_p_annual" ~ "Project",
      type == "closs_reg_annual" ~ "Regional"
    )) %>%
    mutate(
      project = project_i,
      year_c = year - t0,
      year_post = pmax(0, year_c)
    )

  coef_df = closs_long %>%
    group_by(type) %>%
    group_modify(~ {
      mgcv::gam(
        closs_annual ~ year_c + year_post,
        data = .x,
        method = "REML"
      ) |>
        broom::tidy(parametric = T)
    }) %>%
    filter(term %in% c("(Intercept)", "year_c", "year_post")) %>%
    select(type, term, estimate) %>%
    tidyr::pivot_wider(names_from = term, values_from = estimate) %>%
    mutate(
      intercept_at_t0 = `(Intercept)`,
      slope_pre  = year_c,
      slope_post = year_c + year_post
    ) %>%
    select(type, intercept_at_t0, slope_pre, slope_post)

  closs_long_mean = closs_long %>%
    group_by(year, type) %>%
    summarise(closs_annual = mean(closs_annual)) %>%
    ungroup()
  closs_mean_list[[i]] = closs_long_mean %>%
    mutate(
      project = project_i,
      t0 = t0_vec[i]
    )

  closs_plot_i = closs_long_mean %>%
    left_join(coef_df, by = "type") %>%
    mutate(
      fitted = ifelse(
        year < t0,
        intercept_at_t0 + slope_pre  * (year - t0),
        intercept_at_t0 + slope_post * (year - t0))
    ) %>%
    mutate(
      fitted = ifelse(type == "Regional" & year >= t0, NA, fitted),
      project = project_i,
      t0 = t0_vec[i]
    )
  write.csv(closs_plot_i, paste0(out_path, "_closs_annual_plot_", project_i, ".csv"), row.names = F)

  closs_plot_list[[i]] = closs_plot_i
  b = Sys.time()
  cat("Project", i, "/", length(projects), "-", projects[i], "- plot carbon loss rates :", format(difftime(b, a, units = "secs")), "\n")
}

closs_mean = list_rbind(closs_mean_list)
write.csv(closs_mean, paste0(out_path, "_closs_annual_mean.csv"), row.names = F)

closs_plot_list = vector("list", length(projects))
for(i in seq_along(projects)) {
  closs_plot_list[[i]] = read.csv(paste0(out_path, "out_ongoing_closs_annual_plot_", projects[i], ".csv"), header = T)
}
closs_plot = list_rbind(closs_plot_list)
write.csv(closs_plot, paste0(out_path, "closs_annual_plot.csv"), row.names = F)
closs_plot = read.csv(paste0(out_path, "closs_annual_plot.csv"), header = T)

p = ggplot(data = closs_plot, aes(x = year)) +
  geom_point(aes(y = closs_annual, color = type), size = 0.2, na.rm = T) +
  geom_line(aes(y = fitted, color = type), linewidth = 0.8, na.rm = T) +
  geom_vline(aes(xintercept = t0), linetype = "dashed", linewidth = 0.8) +
  geom_hline(yintercept = 0, linetype = "dashed", linewidth = 0.8) +
  facet_wrap(~project, scales = "free_y", ncol = 5, nrow = 6) +
  scale_color_manual(values = c("darkred", "#40B0A6", "#CDAC60"),
                     labels = c("Counterfactual", "Project", "Regional"),
                     name = "Carbon loss rate") +
  labs(x = "Year", y = "Annual carbon loss rate (%)") +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        strip.text = element_text(size = 14),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.position = "bottom")
ggsave(filename = paste0(fig_path, "figure_5_closs_annual.png"),
       plot = p, width = 30, height = 30, units = "cm", dpi = 300)
